root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "tmp/sachapel"
  cmd = "templ generate && go build -buildvcs=false -o tmp/sachapel ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "static", "node_modules"]
  exclude_regex = ["_templ\\.go$"]
  include_ext = ["go", "templ"]
  kill_delay = 0
  send_interrupt = false
  stop_on_error = true

[screen]
  clear_on_rebuild = true

[log]
  time = false
